# Site settings
title: Rob Smith
twitter_username: https://www.linkedin.com/in/robert-smith-53b28438/
name: Rob Smith

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/RobertASmith
 - title: UoS
   url: https://www.sheffield.ac.uk/scharr/staff-pgrs/studentprofiles/robertsmith
 - title: LinkedIn
   url: https://www.linkedin.com/in/robert-smith-53b28438/
 - title: Twitter
   url: https://twitter.com/R06ertSm1th

#Any buzzword skills you want to include
skills:
 - R
 - RShiny
 - STATA
 - Simul8
 - Excel VBA
 - Discrete Event Simulation
 - Microsimulation
 - Cohort Models

#Work experience is required
roles:
 - title: CTO
   start: 2017
   end: Ongoing
   employer: Basement Crowd
   description: Legaltech startup producing a range of innovative legal products. Products include <a href="https://www.juriosity.com" taget="_blank">Juriosity</a>, <a href="https://www.fromcounsel.com" taget="_blank">FromCounsel</a>, <a href="https://www.sparqa.com" taget="_blank">Sparqa</a>.
 - title: Senior Engineer
   start: 2016
   end: 2017
   employer: Emerald Street Ventures
   description: Emerald Street Ventures was established as an incubator vehicle for the development of a number of software and legal-tech projects, and a rapidly growing, London-based start-up using innovative technologies to revolutionise and change the software and legal-tech landscape. Working with a range of cutting edge technologies and techniques including Scala, Cassandra, CoreOS, a variety of Machine Learning techniques.
 - title: Senior Engineer
   start: 2012
   end: 2016
   employer: Covestor
   description: Covestor is an investment marketplace startup that was successfully acquired by Interactive Brokers in 2015. <br/> Working as a senior engineer, I worked closely with the CTO and across the full-stack, I was involved in all aspects of the technology including the website and back-end services.
 - title: Associate Manager
   start: 2005
   end: 2012
   employer: Accenture
   description: Working on a range of functional and technical roles, primarily working on client sites in Financial Services in London and Europe.

#Education is required
education:
 - level: Bachelor of Science (B.Sc.)
   date: 2003
   subject: Artificial Intelligence and Computer Science
   school: University of Birmingham

#List of interesting Github repo/projects to include - optional
github:
 - RobertASmith/RobertASmith.github.io
 - RobertASmith/healthecon_shiny
 - RobertASmith/Intro_to_R
 - RobertASmith/DoPE_Public
 - RobertASmith/covid_bangladesh

intro: |
  Health Economist currently funded by a Wellcome Trust PhD scholarship in Public Health Economics and Decision Science at the University of Sheffield, UK. Open access work can be found here: https://robertasmith.github.io/about_me/ 
  My research is focused on the methods used by economists to estimate the costs and benefits associated with changes in population physical activity, with a specific interest in micro-simulation techniques in R. I have become increasingly interested in the use of data-science to improve the transparency of economic models, and have developed several R-Shiny applications to aid decision makers.
  I teach epidemiology and medical statistics to undergraduates, advanced simulation methods to postgraduates, and 'Introduction to R' as a Short Course. I was a recipient of a Sheffield Sport Scholarship in Athletics.

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>R</strong>: My current role uses Scala as the primary language and have been building applications in Scala for the last two years. I am familiar with a range of Scala libraries, such as <a target="_blank" href="https://automateddeveloper.blogspot.com/2017/12/an-opinionated-guide-to-building-apis.html"> Akka-Http for building microservices</a> and <a target="_blank" href="https://automateddeveloper.blogspot.com/2018/09/generic-programming-with-scala.html"> Shapeless for generic programming</a>, as well as familiar with a range of <a target="_blank" href="https://basementcrowd.com/2018/11/28/scala-the-aux-pattern-path-dependent-types/" >functional programming techniques available</a>.<br/><br/>
   <strong>Simul8</strong>: I am experienced in a variety of Java API’s and frameworks. I have worked with Spring 4, Spring Boot, JPA (Hibernate and EclipseLink) in addition to others. <br/><br/>
   <strong>STATA</strong> I have used Groovy as a language in production for ~4 years and I am familiar with many of the languages features (such as writing <a target='_blank' href="https://dzone.com/articles/functional-programming-groovy">Functional Programming style groovy</a>) and quirks (such as <a target="_blank" href="https://dzone.com/articles/groovy-retrospective-an-addendum-memory-usage-perm">memory leak issues</a>). <br/><br/>
   <strong>Excel VBA</strong>: I have primarily used AWS for running production apps on the cloud. I have experience setting up, configuring and running applications using a range of AWS offerings, including EC2, RDS, S3, Cogito, <a target="_blank" href="https://automateddeveloper.blogspot.com/2018/05/serverless-with-aws-lambda-scala.html">Lambda</a> and its more recent <a target="_blank" href="https://automateddeveloper.blogspot.com/2018/10/machine-learning-with-aws-scala.html">Machine Learning capabilities</a>.<br/><br/>
   <strong>R-Shiny</strong>: I have considerable experience working with R-Shiny to create user interfaces for health economic models. These are being used in a variety of settings including by the WHO Dept Sexual Health.
   <strong>Teaching</strong>: 
