# Site settings
title: Rob Smith
twitter_username: https://www.linkedin.com/in/robert-smith-53b28438/
name: Rob Smith

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/RobertASmith
 - title: UoS
   url: https://www.sheffield.ac.uk/scharr/staff-pgrs/studentprofiles/robertsmith
 - title: LinkedIn
   url: https://www.linkedin.com/in/robert-smith-53b28438/
 - title: Twitter
   url: https://twitter.com/R06ertSm1th
 - title: CV
   url: https://github.com/RobertASmith/RobertASmith.github.io/blob/master/CV_Rob_Smith_OverLeaf.pdf

#Any buzzword skills you want to include
skills:
 - R
 - RShiny
 - STATA
 - Simul8
 - Excel VBA
 - Discrete Event Simulation
 - Microsimulation
 - Cohort Models

#Work experience is required
roles:
 - title: Analyst/Partner
   start: 2019
   end: Ongoing
   employer: Dark Peak Analytics
   description: Collaboration with Dr Paul Schneider providing expertise in health economics, data science & public health. Variety of projects primarily using R to create and adapt public health models and provide user interfaces to aid decision making.
 - title: Public Health Economist
   start: 2018
   end: 2017
   employer: World Health Organisation - Physical Activity Unit
   description: initiated and led a research project developing the methods used in the WHO Europe's Health Economic Assessment Tool for walking and cycling.
 - title: Health Economist
   start: 2016
   end: 2016
   employer: University of Newcastle
   description: I was responsible for the development of a large scale contingent valuation exercise, the results of which are to be used to feed into a resource allocation priority setting exercise for NHS England Dentistry.
 - title: Research Assistant
   start: 2014
   end: 2016
   employer: University of Nottingham
   description: Health economist primarily focused on health services research, in particular the GP Access Scheme. Results of the evaluation were presented to NHS England and the House of Commons Health Select Committee

#Education is required
education:
 - level: PhD
   date: 2016-Ongoing
   subject: Public Health Economics & Decision Science
   school: University of Sheffield
   
education:
 - level: MSc
   date: 2012-2013
   subject: Applied Economics
   school: University of Nottingham
   
education:
 - level: BA
   date: 2009-2012
   subject: Economics
   school: University of Nottingham
   
#List of interesting Github repo/projects to include - optional
github:
 - RobertASmith/RobertASmith.github.io
 - RobertASmith/healthecon_shiny
 - RobertASmith/Intro_to_R
 - RobertASmith/DoPE_Public
 - RobertASmith/covid_bangladesh

intro: |
  I am a health economist currently funded by a Wellcome Trust PhD scholarship in Public Health Economics and Decision Science at the University of Sheffield, UK. My research is focused on the application of methods from health economics and data science to public health. 
  I have a specific interest in physical activity, my PhD focuses on the methods used by economists to estimate the costs and benefits associated with changes in population physical activity, with a specific interest in micro-simulation techniques in R. 
  I have become increasingly interested in the use of data-science to improve the transparency of economic models, and have developed several R-Shiny applications to aid decision makers.
  I teach epidemiology and medical statistics to undergraduates, advanced simulation methods to postgraduates, and 'Introduction to R' as a Short Course. I was a recipient of a Sheffield Sport Scholarship in Athletics.

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>R</strong>: I use R as my main programming language for statistics, health economic evaluation, capacity modelling and geo-spacial analysis.<br/><br/>
   <strong>Simul8</strong>: I teach capacity modelling and health economic evaluation in Simul8.<br/><br/>
   <strong>STATA</strong> I was originally trained as a health economist in STATA, I worked in STATA full time for 3 years before moving to R.<br/><br/>
   <strong>Excel VBA</strong>: I have some limited experience working with Excel VBA.<br/><br/>
   <strong>R-Shiny</strong>: I have considerable experience working with R-Shiny to create user interfaces for health economic models. These are being used in a variety of settings including by the WHO Dept Sexual Health.<br/><br/>
   <strong>Teaching</strong>: I have taught a variety of topics ranging from epidemiology to economics, basic programming in R to R-Shiny for health economics.<br/><br/>
   <strong>Git/GitHub</strong>: All of my projects use Git/GitHub for version control and collaboration. I have experience in teaching Git to new users.<br/><br/>
